export interface JobPosting {
  id: string
  title: string            // "AI Sales Development Representative"
  company: string          // "Acme Corp"
  industry: string         // "B2B SaaS"
  company_size: string     // "11–50 employees"
  category: string         // "Sales"
  budget: string           // "$200–400/month"
  location: string         // "Remote"
  description: string      // Full description
  requirements: string[]   // What the AI needs to do
  preferred: string[]      // Nice to have
  tags: string[]
  posted_days_ago: number
  status: 'open' | 'filled'
  applicants?: number
}

export const MOCK_JOB_POSTINGS: JobPosting[] = [
  {
    id: 'job-1',
    title: 'AI Sales Development Representative',
    company: 'Acme Corp',
    industry: 'B2B SaaS',
    company_size: '11–50 employees',
    category: 'Sales',
    budget: '$200–400/month',
    location: 'Remote',
    description: "We're a fast-growing B2B SaaS company and we're ready to hire our first AI employee. We need an AI SDR to take over our outbound prospecting motion end to end — finding leads, writing personalized emails, managing follow-ups, and booking qualified meetings onto our sales team's calendar. We currently do this manually and it's taking too much of our founders' time. Looking for something that works out of the box with minimal setup.",
    requirements: [
      'Find and qualify leads from LinkedIn, databases, or web scraping',
      'Write personalized cold emails based on prospect data',
      'Manage multi-step follow-up sequences automatically',
      'Handle basic objections and replies',
      'Book qualified meetings directly to our calendar',
      'Integrate with HubSpot or similar CRM',
    ],
    preferred: [
      'Multi-channel outreach (email + LinkedIn)',
      'AI-powered personalization using company-specific data',
      'Reporting and pipeline visibility dashboard',
    ],
    tags: ['Lead Generation', 'Cold Email', 'B2B', 'CRM Integration', 'Meeting Booking'],
    posted_days_ago: 1,
    status: 'open',
    applicants: 3,
  },
  {
    id: 'job-2',
    title: 'AI Lead Agent',
    company: 'GrowthHQ',
    industry: 'Marketing Agency',
    company_size: '2–10 employees',
    category: 'Sales',
    budget: '$100–200/month',
    location: 'Remote',
    description: "Small performance marketing agency looking for an AI employee to manage inbound and outbound lead flow. We generate a lot of leads from ads but struggle to follow up fast enough. We need an AI that can pick up every inbound lead immediately, qualify them, and either book a call or route to the right team member. We also want it to handle light outbound for our own agency new business.",
    requirements: [
      'Respond to inbound leads within seconds of contact',
      'Qualify leads based on predefined criteria (budget, size, need)',
      'Book discovery calls or route to the right team member',
      'Run basic outbound sequences for agency new business',
      'Log all activity in our CRM automatically',
    ],
    preferred: [
      'Works with GoHighLevel or similar agency CRM',
      'SMS and email follow-up capability',
      'Lead scoring dashboard',
    ],
    tags: ['Lead Management', 'Inbound', 'Outbound', 'Agency', 'CRM'],
    posted_days_ago: 2,
    status: 'open',
    applicants: 5,
  },
  {
    id: 'job-3',
    title: 'AI Customer Support Agent',
    company: 'ShopFast',
    industry: 'E-commerce',
    company_size: '11–50 employees',
    category: 'Customer Support',
    budget: '$75–150/month',
    location: 'Remote',
    description: "We run a high-volume Shopify store and our support queue is out of control. We get 300–500 tickets per day and our team can't keep up. We need an AI support agent that can handle tier-1 tickets autonomously — order status, returns, shipping questions, product FAQs — and escalate anything complex to a human. Looking for something we can train on our existing help docs and connect to Shopify.",
    requirements: [
      'Read and categorize incoming support tickets',
      'Respond to common questions instantly (order status, returns, shipping)',
      'Process refund and exchange requests within policy',
      'Escalate complex or sensitive issues to human agents',
      'Integrate with Shopify and Gorgias or similar helpdesk',
    ],
    preferred: [
      'Learn from past ticket history',
      'Multi-language support',
      'CSAT tracking and reporting',
    ],
    tags: ['E-commerce', 'Shopify', 'Helpdesk', 'Tickets', '24/7'],
    posted_days_ago: 3,
    status: 'open',
    applicants: 8,
  },
  {
    id: 'job-4',
    title: 'AI Amazon Product Scout',
    company: 'FBA Kings LLC',
    industry: 'Amazon FBA',
    company_size: '2–10 employees',
    category: 'Amazon FBA',
    budget: '$100–200/month',
    location: 'Remote',
    description: "We're a 7-figure Amazon FBA business looking for an AI employee to take over our product research function. Right now our team manually checks Keepa, Jungle Scout, and competitor listings every day — it takes 3–4 hours and we still miss good opportunities. We want an AI that scans the market daily and delivers a ranked list of sourcing candidates that match our buy box.",
    requirements: [
      'Monitor Amazon categories and search rankings daily',
      'Analyze BSR, review velocity, and competition depth',
      'Estimate margins and potential profitability',
      'Match opportunities to our specific buy box criteria',
      'Deliver a daily email or Slack summary of top finds',
    ],
    preferred: [
      'Integrates with or pulls data from Keepa or Jungle Scout',
      'Tracks seasonal trends and demand curves',
      'Flags new entrants and price drops in tracked categories',
    ],
    tags: ['Amazon', 'FBA', 'Product Research', 'Sourcing', 'Wholesale'],
    posted_days_ago: 4,
    status: 'open',
    applicants: 2,
  },
  {
    id: 'job-5',
    title: 'AI Technical Recruiter',
    company: 'TalentFlow',
    industry: 'HR Tech',
    company_size: '51–200 employees',
    category: 'Recruiting',
    budget: '$300–600/month',
    location: 'Remote',
    description: "We're a fast-growing HR tech startup that's hiring across engineering, product, and GTM — all at once. Our recruiting team is overwhelmed. We need an AI recruiter that can handle sourcing, first-pass resume review, and candidate outreach autonomously, so our human recruiters can focus on final-round interviews and offers. We use Greenhouse as our ATS.",
    requirements: [
      'Source candidates from LinkedIn and job boards based on role criteria',
      'Screen resumes and rank applicants against defined criteria',
      'Send personalized outreach to top candidates',
      'Answer common candidate questions automatically',
      'Schedule interviews and update Greenhouse automatically',
    ],
    preferred: [
      'Native Greenhouse or Lever integration',
      'Diversity-aware sourcing filters',
      'Candidate experience scoring and feedback collection',
    ],
    tags: ['Recruiting', 'Sourcing', 'ATS', 'Technical Hiring', 'Greenhouse'],
    posted_days_ago: 5,
    status: 'open',
    applicants: 4,
  },
  {
    id: 'job-6',
    title: 'AI Market Research Analyst',
    company: 'Meridian Consulting',
    industry: 'Management Consulting',
    company_size: '11–50 employees',
    category: 'Research',
    budget: '$150–300/month',
    location: 'Remote',
    description: "Boutique consulting firm looking for an AI research analyst we can put on retainer. We do strategy and go-to-market work for mid-market companies. Our work is research-heavy — competitive analysis, market sizing, customer sentiment. We want an AI that can take a research brief and return a structured, citation-ready report within hours instead of days.",
    requirements: [
      'Accept research briefs and return structured reports',
      'Research markets, competitors, and customer sentiment online',
      'Size addressable markets using public data',
      'Summarize and synthesize sources into consultant-ready deliverables',
      'Output to Word or PDF format',
    ],
    preferred: [
      'Custom report templates that match our brand',
      'Primary source citation and credibility scoring',
      'Ongoing monitoring of a defined set of companies or markets',
    ],
    tags: ['Research', 'Market Analysis', 'Consulting', 'Reports', 'Competitive Intel'],
    posted_days_ago: 6,
    status: 'open',
    applicants: 1,
  },
  {
    id: 'job-7',
    title: 'AI TikTok Content Creator',
    company: 'Bloom Beauty Co.',
    industry: 'DTC Beauty',
    company_size: '2–10 employees',
    category: 'Marketing',
    budget: '$75–150/month',
    location: 'Remote',
    description: "We're a DTC beauty brand that sells on TikTok Shop and our own Shopify store. TikTok is our primary growth channel but we struggle to post consistently — ideation and scripting takes too long. We want an AI that can generate a week of TikTok content ideas and scripts every Monday morning based on our brand voice, trending sounds, and product catalog.",
    requirements: [
      'Generate 7 TikTok video scripts per week',
      'Write scroll-stopping hooks for each video',
      'Suggest trending sounds and formats relevant to beauty',
      'Match our established brand voice and tone',
      'Include CTAs optimized for TikTok Shop conversion',
    ],
    preferred: [
      'Analyzes trending TikTok content in our niche',
      'Can adapt content for Instagram Reels and YouTube Shorts',
      'Monthly content calendar planning',
    ],
    tags: ['TikTok', 'Content', 'Beauty', 'DTC', 'Scripts', 'Social Media'],
    posted_days_ago: 7,
    status: 'open',
    applicants: 6,
  },
  {
    id: 'job-8',
    title: 'AI Real Estate Deal Finder',
    company: 'PropInvest Capital',
    industry: 'Real Estate Investment',
    company_size: '2–10 employees',
    category: 'Real Estate',
    budget: '$200–400/month',
    location: 'Remote',
    description: "Active real estate investment group focusing on single-family flips and BRRRR deals in the Midwest. We have an acquisition team but they spend most of their time manually reviewing listings instead of building relationships and closing deals. We want an AI that runs our deal analysis process — monitoring MLS, running comps, estimating ARV and rehab costs, and flagging deals that meet our buy box.",
    requirements: [
      'Monitor MLS listings daily in our target markets',
      'Run automated comps and estimate ARV',
      'Estimate rehab budgets based on property details',
      'Filter listings against our buy box (price, ARV spread, area)',
      'Deliver a daily shortlist with a simple investment summary for each',
    ],
    preferred: [
      'Off-market lead identification (absentee owners, distressed properties)',
      'PropStream or Batch Leads data integration',
      'Direct-to-seller outreach automation',
    ],
    tags: ['Real Estate', 'Investing', 'MLS', 'Flipping', 'BRRRR', 'Deal Analysis'],
    posted_days_ago: 8,
    status: 'open',
    applicants: 0,
  },
]
