export interface Listing {
  id: string
  name: string
  creator_name: string
  category: string
  rating: number
  review_count: number
  hire_count: number
  pricing: string
  short_description: string
  full_description: string | null
  what_it_does: string | null
  who_its_for: string | null
  external_link: string
  creator_website: string | null
  demo_video_url: string | null
  tags: string[]
  status: string
  slug?: string
  typical_outcomes?: string[]
  skills?: string[]
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'mock-1',
    name: 'AI Lead Agent',
    creator_name: 'Monday CRM',
    category: 'Sales',
    rating: 4.8,
    review_count: 120,
    hire_count: 340,
    pricing: '$49/month',
    short_description: 'Finds, qualifies, and manages leads automatically. Keeps your pipeline full so your team can focus on closing.',
    full_description: 'The AI Lead Agent is a specialized digital worker built for B2B sales teams. It continuously identifies and qualifies potential customers, organizes your pipeline, and automates follow-ups — so your team spends less time prospecting and more time closing. Powered by Monday CRM\'s infrastructure, it operates 24/7 and delivers actionable pipeline insights daily.',
    what_it_does: 'Finds potential customers matching your ICP\nQualifies leads based on fit and buying signals\nOrganizes contacts and pipeline stages automatically\nAutomates personalized follow-up sequences\nDelivers daily pipeline reports and insights',
    who_its_for: 'Agencies, SaaS founders, consultants, and B2B sales teams that need a steady flow of qualified leads without hiring a full SDR team.',
    typical_outcomes: ['More qualified leads in the pipeline', 'Faster response to inbound interest', 'Better pipeline visibility and forecasting', 'Less time on manual sales admin'],
    skills: ['Lead generation', 'Lead qualification', 'CRM management', 'Pipeline tracking', 'Sales automation'],
    external_link: 'https://monday.com',
    creator_website: 'https://monday.com',
    demo_video_url: null,
    tags: ['Lead Generation', 'CRM', 'Sales Automation', 'Pipeline', 'B2B'],
    status: 'approved',
  },
  {
    id: 'mock-2',
    name: 'AI SDR',
    creator_name: 'Lindy AI',
    category: 'Sales',
    rating: 4.7,
    review_count: 89,
    hire_count: 210,
    pricing: '$79/month',
    short_description: 'An AI sales development rep that researches prospects, writes personalized outreach, and books meetings on autopilot.',
    full_description: 'Lindy\'s AI SDR handles the full top-of-funnel sales motion. It researches prospects across LinkedIn and the web, crafts hyper-personalized outreach, manages multi-step sequences, and books qualified meetings directly onto your calendar. No more cold outreach guesswork.',
    what_it_does: 'Researches prospects using web and LinkedIn data\nWrites personalized cold emails and LinkedIn messages\nManages multi-step outreach sequences\nHandles replies and objections automatically\nBooks meetings directly onto your calendar',
    who_its_for: 'Founders, consultants, and small sales teams that need consistent outbound results without hiring a full-time SDR.',
    typical_outcomes: ['Consistent outbound pipeline', 'Higher reply rates from personalized messaging', 'Meetings booked without manual effort', 'Scalable outreach without scaling headcount'],
    skills: ['Cold outreach', 'Prospect research', 'Email copywriting', 'Sequence management', 'Meeting booking'],
    external_link: 'https://lindy.ai',
    creator_website: 'https://lindy.ai',
    demo_video_url: null,
    tags: ['Outbound', 'Cold Email', 'SDR', 'B2B', 'Meeting Booking'],
    status: 'approved',
  },
  {
    id: 'mock-3',
    name: 'Amazon Product Scout AI',
    creator_name: 'SellerOps AI',
    category: 'Amazon FBA',
    rating: 4.9,
    review_count: 203,
    hire_count: 580,
    pricing: '$99/month',
    short_description: 'Finds profitable Amazon products daily. Analyzes margins, competition, and demand so you can source winners faster.',
    full_description: 'SellerOps\' Amazon Product Scout AI is purpose-built for FBA sellers who want to stop guessing and start finding proven winners. It scans thousands of products daily, analyzes BSR trends, competition depth, and margin potential, then delivers a ranked list of sourcing opportunities straight to your inbox every morning.',
    what_it_does: 'Scans thousands of Amazon categories daily\nAnalyzes BSR, reviews, and competition depth\nCalculates estimated margins and profitability\nFlags seasonal and trending opportunities\nDelivers a ranked opportunity list every morning',
    who_its_for: 'Amazon FBA sellers at any stage who want a reliable product research system without spending hours on manual searches.',
    typical_outcomes: ['Faster product sourcing decisions', 'Higher margin products in your catalog', 'More time for supplier relationships and scaling', 'Reduced risk from bad product picks'],
    skills: ['Product research', 'Amazon marketplace', 'Margin analysis', 'BSR tracking', 'Competitive analysis'],
    external_link: 'https://sellerops.ai',
    creator_website: 'https://sellerops.ai',
    demo_video_url: null,
    tags: ['Amazon', 'FBA', 'Product Research', 'E-commerce', 'Sourcing'],
    status: 'approved',
  },
  {
    id: 'mock-4',
    name: 'TikTok Content AI',
    creator_name: 'CreatorFlow AI',
    category: 'Marketing',
    rating: 4.6,
    review_count: 74,
    hire_count: 190,
    pricing: '$59/month',
    short_description: 'Creates a week of ready-to-post TikTok scripts and hooks in minutes. Built for brands that need to stay consistent on short-form.',
    full_description: 'CreatorFlow\'s TikTok Content AI acts as your dedicated short-form content strategist. Feed it your brand voice, niche, and goals, and it generates a full week of TikTok scripts complete with hooks, structures, CTAs, and trending audio suggestions — all formatted for fast filming.',
    what_it_does: 'Generates weekly TikTok scripts tailored to your niche\nWrites high-converting hooks for each video\nSuggests trending sounds and formats\nAdapts content to your brand tone and audience\nSchedules content calendar with posting times',
    who_its_for: 'E-commerce brands, coaches, and content creators who need to post consistently on TikTok but don\'t have time to ideate and script daily.',
    typical_outcomes: ['Consistent weekly content output', 'Higher view rates from optimized hooks', 'More time for filming and engagement', 'Brand voice consistency across posts'],
    skills: ['TikTok strategy', 'Scriptwriting', 'Hook writing', 'Content planning', 'Trend analysis'],
    external_link: 'https://creatorflow.ai',
    creator_website: 'https://creatorflow.ai',
    demo_video_url: null,
    tags: ['TikTok', 'Short-form', 'Content', 'Social Media', 'Scripts'],
    status: 'approved',
  },
  {
    id: 'mock-5',
    name: 'AI Recruiter',
    creator_name: 'HirePilot AI',
    category: 'Recruiting',
    rating: 4.7,
    review_count: 56,
    hire_count: 130,
    pricing: '$129/month',
    short_description: 'Sources, screens, and schedules candidates automatically. Cuts time-to-hire by handling the top-of-funnel recruiting workflow.',
    full_description: 'HirePilot\'s AI Recruiter takes over the most time-consuming parts of hiring. It searches job boards and LinkedIn for matching candidates, scores them against your criteria, sends personalized outreach, and schedules qualified interviews — all without recruiter intervention.',
    what_it_does: 'Searches job boards and LinkedIn for matching candidates\nScores applicants against your hiring criteria\nSends personalized outreach to top candidates\nAnswers candidate questions automatically\nSchedules interviews on your team\'s calendar',
    who_its_for: 'Startups, agencies, and HR teams that are hiring for multiple roles and want to reduce time-to-hire without growing the recruiting team.',
    typical_outcomes: ['Faster time-to-hire across open roles', 'Higher quality candidates in the pipeline', 'Recruiter time freed up for offers and closing', 'Consistent candidate experience at scale'],
    skills: ['Candidate sourcing', 'Resume screening', 'Outreach writing', 'Interview scheduling', 'Applicant tracking'],
    external_link: 'https://hirepilot.ai',
    creator_website: 'https://hirepilot.ai',
    demo_video_url: null,
    tags: ['Recruiting', 'Hiring', 'HR', 'Sourcing', 'Interviews'],
    status: 'approved',
  },
  {
    id: 'mock-6',
    name: 'Market Research Analyst AI',
    creator_name: 'InsightBot AI',
    category: 'Research',
    rating: 4.8,
    review_count: 41,
    hire_count: 95,
    pricing: '$69/month',
    short_description: 'Researches markets, competitors, and trends on demand. Delivers structured reports you can act on — in minutes, not days.',
    full_description: 'InsightBot\'s Market Research Analyst AI does deep-dive research on any market, competitor, or trend. Submit a research brief and receive a structured report with market sizing, competitive landscape analysis, customer sentiment, and strategic recommendations — all sourced from live data.',
    what_it_does: 'Researches markets, competitors, and trends on demand\nAnalyzes customer reviews and sentiment across platforms\nBuilds competitive landscape summaries\nSizes markets using public data and proxies\nDelivers structured reports with actionable insights',
    who_its_for: 'Founders, investors, product teams, and consultants that need fast, reliable market intelligence without a dedicated research budget.',
    typical_outcomes: ['Faster strategic decisions', 'Deeper competitive understanding', 'Customer insight without running surveys', 'Research that used to take weeks done in hours'],
    skills: ['Market research', 'Competitive analysis', 'Sentiment analysis', 'Report writing', 'Data synthesis'],
    external_link: 'https://insightbot.ai',
    creator_website: 'https://insightbot.ai',
    demo_video_url: null,
    tags: ['Research', 'Market Analysis', 'Competitive Intel', 'Reports', 'Strategy'],
    status: 'approved',
  },
  {
    id: 'mock-7',
    name: 'Customer Support Agent AI',
    creator_name: 'SupportDesk AI',
    category: 'Customer Support',
    rating: 4.6,
    review_count: 167,
    hire_count: 420,
    pricing: '$39/month',
    short_description: 'Handles customer questions, complaints, and refund requests 24/7. Resolves up to 80% of tickets without human involvement.',
    full_description: 'SupportDesk\'s AI handles tier-1 customer support autonomously. It reads and responds to incoming tickets, resolves common issues like refunds, tracking, and account changes, escalates complex cases to humans, and maintains tone consistency across every interaction — 24 hours a day.',
    what_it_does: 'Reads and categorizes incoming support tickets\nResponds to common questions instantly and accurately\nProcesses refunds, exchanges, and account changes\nEscalates complex or sensitive issues to your team\nMaintains consistent tone across all conversations',
    who_its_for: 'E-commerce brands, SaaS products, and service businesses that receive high ticket volume and want to reduce response times without growing their support team.',
    typical_outcomes: ['80%+ of tickets resolved without human input', 'Sub-minute response times around the clock', 'Reduced support team workload', 'Higher customer satisfaction scores'],
    skills: ['Customer support', 'Ticket management', 'Refund processing', 'Escalation logic', 'Tone matching'],
    external_link: 'https://supportdesk.ai',
    creator_website: 'https://supportdesk.ai',
    demo_video_url: null,
    tags: ['Support', 'Customer Service', 'Helpdesk', '24/7', 'Ticketing'],
    status: 'approved',
  },
  {
    id: 'mock-8',
    name: 'Real Estate Deal Finder AI',
    creator_name: 'PropScout AI',
    category: 'Real Estate',
    rating: 4.9,
    review_count: 38,
    hire_count: 88,
    pricing: '$149/month',
    short_description: 'Scans MLS listings and off-market sources daily to surface undervalued properties that match your investment criteria.',
    full_description: 'PropScout\'s Deal Finder AI is a dedicated real estate analyst that works around the clock. It monitors MLS listings, Zillow, and off-market sources, runs comps, estimates ARV and repair budgets, and delivers a shortlist of deals that match your buy box — every single day.',
    what_it_does: 'Monitors MLS and off-market listings daily\nRuns automated comps to estimate ARV\nEstimates rehab budgets based on property condition\nFilters deals by your buy box criteria\nDelivers a daily shortlist with investment summaries',
    who_its_for: 'Real estate investors, wholesalers, and agents who want to find more deals without spending hours on manual research.',
    typical_outcomes: ['More deal flow without more hours worked', 'Faster offer-ready analysis on each property', 'Higher conviction on acquisitions', 'Competitive edge from off-market access'],
    skills: ['Deal analysis', 'MLS monitoring', 'ARV estimation', 'Market comps', 'Investment criteria matching'],
    external_link: 'https://propscout.ai',
    creator_website: 'https://propscout.ai',
    demo_video_url: null,
    tags: ['Real Estate', 'Investing', 'MLS', 'Deal Finding', 'Wholesaling'],
    status: 'approved',
  },
]
